import Head from "next/head";
import AllServices from "@/components/AllServices";
import Banner from "@/components/Banner";
import Banner2 from "@/components/Banner2";
import Emailus from "@/components/Emailus";
import Growth from "@/components/Growth";
import Services from "@/components/Services";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// import styles from "@/styles/Home.module.css";

export default function Home() {
  
  return (
    <>
      <Head>
        <title>KazianaMedia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
        <Banner />
        <Banner2 />
        <Growth />
        <Services/>
        <AllServices/>
        <Emailus/>

        </div>
      </main>
    </>
  );
}
